### ISSUE TITLE
Błąd logowania

### ISSUE THREAD

**Issue by naczo5** [KartoniarzEssa/BetterOdrabiamyDownloader#5]
Od dzisiaj nie mogłem zalogować się w skrypcie nie ważne jakiego konta,ip lub systemu użyłem. Wczoraj jeszcze działało a nic sie w kodzie w międzyczasie nie zmieniło więc zakładam że to zmiana po stronie odrabiamy. 

User
3Traceback (most recent call last):
  File "/home/naczo/Desktop/BetterOdrabiamyDownloader-main/BetterOdrabiamyDownloader.py", line 202, in <module>
    token = get_token(user, password)
  File "/home/naczo/Desktop/BetterOdrabiamyDownloader-main/BetterOdrabiamyDownloader.py", line 149, in get_token
    token = json.loads(rpost)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MichalKaniowski** [comment]
Mam to samo. Wywala error przy pobieraniu sesji z api/v2/sessions i innych endpointach.

**Comment by PawiX25** [comment]
Mam ten sam problem, Czy jest coś, co można zrobić, aby to naprawić?
